// Additional one-time or manually managed events for the map and event sections
// Extend this array as needed for other cities/events

import type { Event } from '@/components/FeaturedEvents';

export const ADDITIONAL_EVENTS: Event[] = [
  {
    type: 'Conference',
    id: 100011,
    date_add: Date.now(),
    date: '09.10.2025',
    time: '9:00',
    name: 'ViteConf Amsterdam - Day 1',
    url: 'https://viteconf.amsterdam/',
    rsvp: 'https://viteconf.amsterdam/',
    city: 'Amsterdam',
    address: 'Lief Amsterdam, Basisweg 63, 1043 AN Amsterdam',
    image: '',
    serie: 'Vite',
    topic: ['Vite', 'JavaScript', 'Web Development', 'Frontend', 'Build Tools'],
  },
  {
    type: 'Conference',
    id: 100012,
    date_add: Date.now(),
    date: '10.10.2025',
    time: '9:00',
    name: 'ViteConf Amsterdam - Day 2',
    url: 'https://viteconf.amsterdam/',
    rsvp: 'https://viteconf.amsterdam/',
    city: 'Amsterdam',
    address: 'Lief Amsterdam, Basisweg 63, 1043 AN Amsterdam',
    image: '',
    serie: 'Vite',
    topic: ['Vite', 'JavaScript', 'Web Development', 'Frontend', 'Build Tools'],
  },
  {
    type: 'Meetup',
    id: 100014,
    date_add: Date.now(),
    date: '10.10.2025',
    time: '19:00',
    name: 'ViteConf Amsterdam - Conference Party',
    url: 'https://viteconf.amsterdam/',
    rsvp: 'https://viteconf.amsterdam/',
    city: 'Amsterdam',
    address: 'Lief Amsterdam, Basisweg 63, 1043 AN Amsterdam',
    image: '',
    serie: 'Vite',
    topic: ['Vite', 'JavaScript', 'Networking', 'Party'],
  },
  {
    type: 'Conference',
    id: 100009,
    date_add: Date.now(),
    date: '07.10.2025',
    time: '9:00',
    name: 'React Conference - Day 1',
    url: 'https://conf.react.dev/',
    rsvp: 'https://conf.react.dev/',
    city: 'On-line',
    address: 'Virtual Event',
    image: '',
    serie: 'React',
    topic: ['React', 'JavaScript', 'Web Development', 'Frontend'],
  },
  {
    type: 'Conference',
    id: 100010,
    date_add: Date.now(),
    date: '08.10.2025',
    time: '9:00',
    name: 'React Conference - Day 2',
    url: 'https://conf.react.dev/',
    rsvp: 'https://conf.react.dev/',
    city: 'On-line',
    address: 'Virtual Event',
    image: '',
    serie: 'React',
    topic: ['React', 'JavaScript', 'Web Development', 'Frontend'],
  },
  {
    type: 'Meetup',
    id: 99998,
    date_add: Date.now(),
    date: '15.05.2025',
    time: '17:30',
    name: 'Gdańsk TypeScript Meetup',
    url: 'https://www.meetup.com/gdansk-typescript/events/307232721/',
    rsvp: 'https://www.meetup.com/gdansk-typescript/events/307232721/',
    city: 'Gdańsk',
    address: 'DevOne Hub, Aleja Grunwaldzka 411',
    image: '',
    serie: 'TypeScript',
    topic: ['TypeScript', 'JavaScript'],
  },
  {
    type: 'Meetup',
    id: 99999,
    date_add: Date.now(),
    date: '02.09.2025',
    time: '18:00',
    name: 'AI Meetup in Wroclaw with Callstack & Vercel',
    url: 'https://www.callstack.com/events/ai-meetup-in-wroclaw-first-edition',
    rsvp: 'https://www.callstack.com/events/ai-meetup-in-wroclaw-first-edition',
    city: 'Wrocław',
    address: 'Concordia Design',
    image: '',
    serie: 'AI',
    topic: ['AI', 'React Native', 'JavaScript', 'React'],
  },
  {
    type: 'Conference',
    id: 100000,
    date_add: Date.now(),
    date: '27.10.2025',
    time: '8:30',
    name: 'FutureConf 2025',
    url: 'https://futureconf.tech/',
    rsvp: 'https://futureconf.tech/',
    city: 'Kraków',
    address: 'Międzynarodowe Centrum Kultury\nRynek Główny 25',
    image: '',
    serie: 'AI & Future Tech',
    topic: ['AI', 'Machine Learning', 'JavaScript', 'Future Technologies'],
  },
  {
    type: 'Meetup',
    id: 100001,
    date_add: Date.now(),
    date: '17.09.2025',
    time: '17:00',
    name: 'AI Miners',
    url: 'https://aiminers.pl',
    rsvp: 'https://luma.com/35s646kw',
    city: 'Katowice',
    address: 'Rawa.Ink',
    image: '',
    serie: 'AI',
    topic: ['AI', 'Machine Learning', 'Business', 'Networking'],
  },
  {
    type: 'Meetup',
    id: 100002,
    date_add: Date.now(),
    date: '02.10.2025',
    time: '17:30',
    name: 'Gdańsk TypeScript Meetup #16 / meet.js by Handsontable',
    url: 'https://www.meetup.com/gdansk-typescript/events/310970083/',
    rsvp: 'https://www.meetup.com/gdansk-typescript/events/310970083/',
    city: 'Gdańsk',
    address: 'DevOne Hub, Aleja Grunwaldzka 411',
    image: '',
    serie: 'TypeScript',
    topic: ['TypeScript', 'JavaScript', 'Accessibility', 'Architecture'],
  },
  {
    type: 'Conference',
    id: 100003,
    date_add: Date.now(),
    date: '06.10.2025',
    time: '9:00',
    name: 'Testing Ground Conference 2025',
    url: 'https://testingground.pl/',
    rsvp: 'https://testingground.pl/',
    city: 'Warszawa',
    address: 'Sound Garden Hotel\nŻwirki i Wigury 18, 02-092 Warszawa',
    image: '',
    serie: 'Quality & Testing',
    topic: ['Testing', 'QA', 'Security', 'Accessibility', 'Quality Assurance'],
  },
  {
    type: 'Conference',
    id: 100004,
    date_add: Date.now(),
    date: '04.10.2025',
    time: '18:00',
    name: 'HackYeah 2025',
    url: 'https://hackyeah.pl/',
    rsvp: 'https://hackyeah.pl/',
    city: 'Kraków',
    address: 'TAURON Arena Kraków\nul. Stanisława Lema 7, 31-571 Kraków',
    image: '',
    serie: 'Hackathon',
    topic: [
      'Hackathon',
      'Programming',
      'Innovation',
      'Collaboration',
      'AI',
      'Biohacking',
    ],
  },
  {
    type: 'Conference',
    id: 100005,
    date_add: Date.now(),
    date: '02.10.2025',
    time: '15:00',
    name: 'JetBrains JavaScript Day 2025 (5th Edition)',
    url: 'https://lp.jetbrains.com/javascript-day-2025/',
    rsvp: 'https://lp.jetbrains.com/javascript-day-2025/',
    city: 'On-line',
    address: 'Free Online Event',
    image: '',
    serie: 'JavaScript',
    topic: [
      'JavaScript',
      'Web Development',
      'Expert Talks',
      'Live Q&A',
      'Community',
      'Best Practices',
    ],
  },
  {
    type: 'Conference',
    id: 100006,
    date_add: Date.now(),
    date: '13.10.2025',
    time: '9:00',
    name: 'The Hack Summit 2025 - Online',
    url: 'https://thehacksummit.com/',
    rsvp: 'https://thehacksummit.com/',
    city: 'On-line',
    address: 'Online Event',
    image: '',
    serie: 'Cybersecurity',
    topic: [
      'Cybersecurity',
      'Hacking',
      'AI',
      'Cloud Security',
      'DevSecOps',
      'OSINT',
      'Forensics',
    ],
  },
  {
    type: 'Conference',
    id: 100007,
    date_add: Date.now(),
    date: '14.10.2025',
    time: '9:00',
    name: 'The Hack Summit 2025',
    url: 'https://thehacksummit.com/',
    rsvp: 'https://thehacksummit.com/',
    city: 'Warszawa',
    address: 'PGE Narodowy\nal. Ks. Józefa Poniatowskiego 1',
    image: '',
    serie: 'Cybersecurity',
    topic: [
      'Cybersecurity',
      'Hacking',
      'AI',
      'Cloud Security',
      'DevSecOps',
      'OSINT',
      'Forensics',
    ],
  },
  {
    type: 'Meetup',
    id: 100008,
    date_add: Date.now(),
    date: '09.10.2025',
    time: '18:00',
    name: 'Spotkanie dla organizatorów wydarzeń #4',
    url: 'https://crossweb.pl/wydarzenia/spotkanie-dla-organizatorow-wydarzen-4/',
    rsvp: 'https://crossweb.pl/wydarzenia/spotkanie-dla-organizatorow-wydarzen-4/',
    city: 'Kraków',
    address: 'Giona Coffee&Pizza Al. Pokoju 1A',
    image: '',
    serie: 'Event Organizers',
    topic: ['Event Management', 'Networking', 'Community', 'Barcamp'],
  },
  {
    type: 'Meetup',
    id: 100013,
    date_add: Date.now(),
    date: '29.10.2025',
    time: '16:30',
    name: 'AI Miners #2',
    url: 'https://aiminers.pl',
    rsvp: 'https://aiminers.pl',
    city: 'Katowice',
    address: 'Miejski Inkubator Przedsiębiorczości Rawa.Ink',
    image: 'https://aiminers.pl/logo.png',
    serie: 'AI',
    topic: ['AI', 'Machine Learning', 'Business', 'Networking', 'Automation'],
  },
];
