import { Promo } from '../types/promo';

export const eventsDiscounts: Promo[] = [
  {
    id: 'infoshare-2025',
    name: 'InfoShare 2025',
    message: '10% off with code ISC25-MeetJS10!',
    cta: '👉 Get 10% Off',
    ticketLink:
      'https://infoshare.pl/is-register/?discount_code=ISC25-MeetJS10',
    eventLink: 'https://infoshare.pl',
    expiresAt: '2025-05-24T23:59:59+02:00',
    description:
      'Join InfoShare 2025, one of the largest tech conferences in Central Europe! Use code ISC25-MeetJS10 for 10% off your ticket.',
    gradient: 'bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600',
    icon: '🎟️',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Gdańsk',
    discountCode: 'ISC25-MeetJS10',
  },
  {
    id: 'code-europe-2025',
    name: 'Code Europe 2025',
    message: "Join Poland's biggest tech festival with code MEETJS25!",
    cta: '👉 Get Discount',
    ticketLink: 'https://www.codeeurope.pl/en/',
    eventLink: 'https://www.codeeurope.pl/en/',
    expiresAt: '2025-06-30T23:59:59+02:00',
    description:
      "Join Poland's biggest tech festival! Code Europe 2025 takes place on June 30 - July 1, 2025 at EXPO Kraków. Experience inspiring talks, workshops, and networking opportunities with tech leaders and innovators. Use code MEETJS25 for a special discount on tickets!",
    gradient: 'bg-gradient-to-r from-purple-600 via-blue-500 to-indigo-600',
    icon: '🎪',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Kraków',
    discountCode: 'MEETJS25',
  },
  {
    id: 'ms-tech-summit-2025',
    name: 'MS Tech Summit 2025',
    message: '30% off with code MSTS25xmeetjs!',
    cta: '👉 Get 30% Off',
    ticketLink: 'https://mstechsummit.pl/',
    eventLink: 'https://mstechsummit.pl/',
    expiresAt: '2025-06-10T23:59:59+02:00',
    description:
      'MS Tech Summit 2025 is one of the few community conferences in Poland fully dedicated to Microsoft technologies. Join online on June 11 and in-person in Warsaw on June 12, 2025. Use code MSTS25xmeetjs for 30% off Standard and Exec packages!',
    gradient: 'bg-gradient-to-r from-blue-500 via-cyan-400 to-blue-600',
    icon: '🧠',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Warsaw',
    discountCode: 'MSTS25xmeetjs',
  },
  {
    id: 'devdays-europe-2025',
    name: 'DevDays Europe 2025',
    message: '15% off with code meet.js15!',
    cta: '👉 Get 15% Off',
    ticketLink: 'https://devdays.lt',
    eventLink: 'https://devdays.lt',
    expiresAt: '2025-05-19T23:59:59+02:00',
    description:
      'DevDays Europe is back for its 7th edition! Join us in Vilnius & online on May 20-23, 2025, for full-day workshops, 90+ content-packed sessions, global networking with 700+ participants, EXPO, and more! Use code FINAL15 for 15% off.',
    gradient: 'bg-gradient-to-r from-indigo-600 via-blue-500 to-cyan-400',
    icon: '👨🏻‍💻',
    emojiRight: '🇱🇹',
    country: 'Lithuania',
    city: 'Vilnius',
    discountCode: 'meet.js15',
  },
  {
    id: 'cityjs-athens-2025',
    name: 'CityJS Athens 2025',
    message: 'Use meet.js promo code for a discount!',
    cta: '👉 Get Discount',
    ticketLink:
      'https://ti.to/cityjs-conference/cityjs-athens-2025/discount/meetjs',
    eventLink: 'https://cityjsconf.org/athens',
    expiresAt: '2025-05-24T23:59:59+02:00',
    description:
      'CityJS Athens brings together JavaScript developers for two days of talks, workshops and networking in the heart of Greece. Join experts and enthusiasts to explore the latest in JS frameworks, tools, and best practices.',
    gradient: 'bg-gradient-to-r from-blue via-purple to-green',
    icon: '🚀',
    emojiRight: '🇬🇷',
    country: 'Greece',
    city: 'Athens',
    discountCode: 'meetjs',
  },
  {
    id: 'appjs-2025',
    name: 'App.js 2025',
    message: 'Exclusive 15% discount for meet.js community!',
    cta: '👉 Get 15% Off',
    ticketLink: 'https://ti.to/appjs/2025/discount/meetJS',
    eventLink: 'https://appjs.co',
    expiresAt: '2025-05-27T23:59:59+02:00',
    description:
      "App.js is Poland's premier conference focused on JavaScript for mobile and web applications. Join us in Kraków for hands-on workshops, in-depth technical talks, and networking with the top JS developers building modern applications.",
    gradient: 'bg-gradient-to-r from-indigo-500 via-blue-500 to-purple-500',
    icon: '📱',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Kraków',
    discountCode: 'meetJS',
  },
  {
    id: 'react-universe-2025',
    name: 'React Universe Conf 2025',
    message: '10% off with code meet.js10!',
    cta: '👉 Get Discount',
    ticketLink: 'https://ti.to/RUC/react-universe-conf-2025/discount/meet.js10',
    workshopLink: 'https://www.reactuniverseconf.com/workshops-2025',
    eventLink: 'https://www.reactuniverseconf.com/',
    expiresAt: '2025-09-02T23:59:59+02:00',
    description:
      'React Universe is the largest React conference in Central Europe, bringing together the global React community in Wrocław, Poland. Featuring speakers from Meta and leading React teams, this event covers everything from React core concepts to advanced patterns and the React ecosystem.',
    workshopDescription:
      'Exclusive workshop on Day 0 (Sep 2, 2025): "Vercel AI SDK v5: Building AI-powered Apps in TypeScript" by Matt Pocock. Use code COMBO for €70 off the workshop when purchased with your conference ticket.',
    gradient: 'bg-gradient-to-r from-yellow-400 via-orange-500 to-pink-500',
    icon: '🪐',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Wrocław',
    discountCode: 'meet.js10',
    workshopDiscountCode: 'COMBO',
  },
  {
    id: 'wearedevelopers-2025',
    name: 'WeAreDevelopers World Congress 2025',
    message: '10% off with code Community_MeetJs!',
    cta: '👉 Get 10% Off',
    ticketLink:
      'https://www.wearedevelopers.com/world-congress?discount=Community_MeetJs',
    eventLink: 'https://www.wearedevelopers.com/world-congress',
    expiresAt: '2025-07-11T23:59:59+02:00',
    description:
      "Join the WeAreDevelopers World Congress 2025 (July 10-11), the world's leading event for developers, AI innovators & tech leaders! Connect with 15,000+ developers, 500+ speakers including GitHub CEO Thomas Dohmke, Amazon CTO Dr. Werner Vogels, and legendary game creator John Romero. Experience cutting-edge talks on AI, software development, and the future of technology. Use code Community_MeetJs for 10% off your ticket.",
    gradient: 'bg-gradient-to-r from-orange-500 via-red-500 to-pink-600',
    icon: '🌍',
    emojiRight: '🇩🇪',
    country: 'Germany',
    city: 'Berlin',
    discountCode: 'Community_MeetJs',
  },
  {
    id: 'vueconfus-2025',
    name: 'VueConf US 2025',
    message: 'Use code VUE25MEETJS for a special discount!',
    cta: '👉 Redeem Voucher',
    ticketLink:
      'https://reg.connectevents.io/ConnectEvents/Vueconfus2025/redeem?voucher=VUE25MEETJS',
    eventLink: 'https://vueconf.us',
    expiresAt: '2025-05-21T23:59:59+02:00',
    description:
      'VueConf US is the premier Vue.js conference in North America, held in New Orleans on May 20-21, 2025. Join for two days of code playground, talks, and networking with the Vue community. Optional workshop day available on May 19. Save $199 with our exclusive discount!',
    gradient: 'bg-gradient-to-r from-green-400 via-blue-500 to-purple-500',
    icon: '🟩',
    emojiRight: '🇺🇸',
    country: 'USA',
    city: 'New Orleans',
    discountCode: 'VUE25MEETJS',
  },
  {
    id: 'summit-community-partner-2025',
    name: 'Women in Tech Summit',
    message: 'Use code SUMMIT_2025MEET.JS50 by May 17!',
    cta: '👉 Get tickets',
    ticketLink: 'https://go.womenintechsummit.pl/buy?inperson=1',
    eventLink: 'https://womenintechsummit.pl/join-the-event',
    expiresAt: '2025-05-17T23:59:59+02:00',
    description:
      'As a Community Partner for the Women in Tech Summit, meet.js members can use code SUMMIT_2025MEET.JS50 for 50% off tickets until May 17, 2025. Free tickets are also available - grab them as soon as possible for the best experience! The Summit offers networking with tech professionals, inspiring talks, and workshops. Join us and be part of this empowering event!',
    gradient: 'bg-gradient-to-r from-pink-500 via-yellow-400 to-purple-500',
    icon: '👧',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Warsaw',
    discountCode: 'SUMMIT_2025MEET.JS50',
  },
  {
    id: 'react-summit-2025',
    name: 'React Summit 2025',
    message: '10% off with code REACT!',
    cta: '👉 Get 10% Off',
    ticketLink: 'https://ti.to/gitnation/react-summit-2025/discount/REACT',
    eventLink: 'https://gitnation.com/events/react-summit-2025',
    expiresAt: '2025-05-31T23:59:59+02:00',
    description:
      'React Summit 2025 brings together the global React community for an immersive experience with expert-led sessions and networking opportunities. Use code REACT for 10% off on tickets!',
    gradient: 'bg-gradient-to-r from-blue-600 via-indigo-500 to-purple-500',
    icon: '⚛️',
    emojiRight: '🇳🇱',
    country: 'Netherlands',
    city: 'Amsterdam',
    discountCode: 'REACT',
  },
  {
    id: 'react-summit-us-2025',
    name: 'React Summit US 2025',
    message: '10% off with code FRIENDS!',
    cta: '👉 Get 10% Off',
    ticketLink: 'https://ti.to/gitnation/react-summit-us-2025/discount/FRIENDS',
    eventLink: 'https://gitnation.com/events/react-summit-us-2025',
    expiresAt: '2025-11-17T23:59:59+02:00',
    description:
      'React Summit US 2025 is the premier React conference in North America taking place November 18-21, 2025 in New York & Online. Join the global React community for expert-led sessions and networking. Use code FRIENDS for 10% off on tickets!',
    gradient: 'bg-gradient-to-r from-red-500 via-blue-500 to-indigo-600',
    icon: '⚛️',
    emojiRight: '🇺🇸',
    country: 'USA',
    city: 'New York',
    discountCode: 'FRIENDS',
  },
  {
    id: 'warsawjs-2025',
    name: 'WarsawJS',
    message: '40% off with code JScommunity!',
    cta: '👉 Get 40% Off',
    ticketLink:
      'https://app.easycart.pl/checkout/warsawjs/meetup-127?promo=JScommunity',
    eventLink: 'https://warsawjs.com/',
    expiresAt: '2025-06-09T23:59:59+02:00',
    description:
      'Our friendly meetup friends, WarsawJS, offer a 40% discount with code JScommunity for their meetup!',
    gradient: 'bg-gradient-to-r from-red-500 via-pink-500 to-purple-600',
    icon: '🤝',
    image:
      'https://warsawjs.com/static/images/logos/logo-warsawjs-with-white-text.svg',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Warsaw',
    discountCode: 'JScommunity',
  },
  {
    id: 'futureconf-2025',
    name: 'FutureConf 2025',
    message: 'Up to 50% off with group discount system!',
    cta: '👉 Get Group Discount',
    ticketLink: 'https://futureconf.tech/meetjs/',
    eventLink: 'https://futureconf.tech/',
    expiresAt: '2025-10-28T23:59:59+02:00',
    description:
      'A two-day conference in the heart of Kraków – FutureConf 2025 takes place October 27-28 at the International Cultural Centre on the Main Square. The theme of Future 2025 is "AI in Production". The agenda features a mix of topics: from ML/AI to security and practical AI production use cases. Speakers include Mateusz Chrobok, Vladimir Alekseichenko, Ziemowit Dworakowski from AGH, Merve Noyan from Hugging Face, Sacha Bron from Llamaindex, Kacper Milan from mBank, and specialists from Docker, Qdrant, and Box. Buy your ticket and share with friends – each additional person increases the discount up to 50%!',
    gradient: 'bg-gradient-to-r from-purple-600 via-indigo-500 to-blue-600',
    icon: '🤖',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Kraków',
    discountCode: 'Group discount system',
  },
  {
    id: 'ai-miners-2025',
    name: 'AI Miners',
    message: '10% off with code MEETJS-10!',
    cta: '👉 Get 10% Off',
    ticketLink: 'https://luma.com/35s646kw?coupon=MEETJS-10',
    eventLink: 'https://aiminers.pl',
    expiresAt: '2025-09-17T23:59:59+02:00',
    description:
      'AI Miners to spotkania praktyków AI z biznesem w Katowicach. Realne wdrożenia, konkretne rozwiązania, wartościowe dyskusje. Wydarzenie łączy praktyków - developerów, inżynierów, founderów - z przedstawicielami biznesu, którzy chcą zrozumieć, jak naprawdę działa sztuczna inteligencja w produktach i procesach. Use code MEETJS-10 for 10% off your ticket!',
    gradient: 'bg-gradient-to-r from-orange-500 via-red-500 to-purple-600',
    icon: '⛏️',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Katowice',
    discountCode: 'MEETJS-10',
  },
  {
    id: 'testing-ground-2025',
    name: 'Testing Ground Conference 2025',
    message: '15% off with code meet.js15!',
    cta: '👉 Get 15% Off',
    ticketLink: 'https://testingground.pl/',
    eventLink: 'https://testingground.pl/',
    expiresAt: '2025-10-06T23:59:59+02:00',
    description:
      'Testing Ground Conference 2025 is a prestigious two-day event taking place October 6-7, 2025 in Warsaw. The conference theme is "Quality without compromise, security without exceptions, accessibility for everyone." Join 16 inspiring presentations and 6 practical workshops led by recognized experts. Perfect for QA professionals, security specialists, and those passionate about creating accessible digital products. Use code meet.js15 for 15% off your ticket!',
    gradient: 'bg-gradient-to-r from-green-500 via-teal-500 to-blue-600',
    icon: '🧪',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Warsaw',
    discountCode: 'meet.js15',
  },
  {
    id: 'hackyeah-2025',
    name: 'HackYeah 2025',
    message: 'Największy stacjonarny hackathon w Europie - darmowy udział!',
    cta: '👉 Zarejestruj się',
    ticketLink: 'https://hackyeah.pl/',
    eventLink: 'https://hackyeah.pl/',
    expiresAt: '2025-10-05T23:59:59+02:00',
    description:
      'HackYeah 2025 to największy w Europie stacjonarny hackathon, który odbędzie się 4-5 października 2025 roku w TAURON Arena w Krakowie. Przez 24 godziny setki programistów, designerów i pasjonatów nowych technologii zmierzą się z wyzwaniami wymagającymi szybkiego myślenia, współpracy i niebanalnych rozwiązań. Wydarzenie obejmuje biohacking, podróże, obronność oraz rozwiązania mające realny wpływ na codzienne życie. Równolegle odbędzie się konferencja technologiczna z ekspertami IT. Udział jest całkowicie darmowy - wystarczy wcześniejsza rejestracja. Mogą uczestniczyć osoby pełnoletnie indywidualnie lub w zespołach do 6 osób.',
    gradient: 'bg-gradient-to-r from-orange-600 to-pink-600',
    icon: '💻',
    emojiRight: '🇵🇱',
    country: 'Poland',
    city: 'Kraków',
    discountCode: 'FREE',
  },
];
