import { Promo } from '../components/PromoBanners';

export const promos: Promo[] = [
	{
		id: 'cityjs-athens-2025',
		message: 'CityJS Athens 2025: Use our promo code for a discount!',
		cta: '👉 Get Discount',
		link: 'https://ti.to/cityjs-conference/cityjs-athens-2025/discount/meetjs',
		expiresAt: '2025-05-24T23:59:59+02:00',
		gradient: 'bg-gradient-to-r from-blue via-purple to-green',
		icon: '🚀',
		emojiRight: '🇬🇷',
		country: 'Greece',
		city: 'Athens',
	},
	{
		id: 'react-universe-2025',
		message: 'React Universe Conf 2025: 10% off with code meet.js10!',
		cta: '👉 Get Discount',
		link: 'https://ti.to/RUC/react-universe-conf-2025/discount/meet.js10',
		expiresAt: '2025-09-02T23:59:59+02:00',
		gradient: 'bg-gradient-to-r from-yellow-400 via-orange-500 to-pink-500',
		icon: '🪐',
		emojiRight: '🇵🇱',
		country: 'Poland',
		city: 'Wrocław',
	},
	{
		id: 'vueconfus-2025',
		message: 'VueConf US 2025: Use code VUE25MEETJS for a special discount!',
		cta: '👉 Redeem Voucher',
		link: 'https://reg.connectevents.io/ConnectEvents/Vueconfus2025/redeem?voucher=VUE25MEETJS',
		expiresAt: '2025-05-21T23:59:59+02:00',
		gradient: 'bg-gradient-to-r from-green-400 via-blue-500 to-purple-500',
		icon: '🟩',
		emojiRight: '🇺🇸',
		country: 'USA',
		city: 'New Orleans',
	},
];
