import { Promo } from '../types/promo';

export const promos: Promo[] = [
	{
		id: 'devdays-europe-2025',
		message: 'DevDays Europe 2025: 15% off with code meet.js15!',
		cta: '👉 Get 15% Off',
		ticketLink: 'https://devdays.lt',
		eventLink: 'https://devdays.lt',
		expiresAt: '2025-05-19T23:59:59+02:00',
		description:
			'DevDays Europe is back for its 7th edition! Join us in Vilnius & online on May 20-23, 2025, for full-day workshops, 90+ content-packed sessions, global networking with 700+ participants, EXPO, and more! Use code FINAL15 for 15% off.',
		gradient: 'bg-gradient-to-r from-indigo-600 via-blue-500 to-cyan-400',
		icon: '👨🏻‍💻',
		emojiRight: '🇱🇹',
		country: 'Lithuania',
		city: 'Vilnius',
		discountCode: 'meet.js15',
	},
	{
		id: 'cityjs-athens-2025',
		message: 'CityJS Athens 2025: Use meet.js promo code for a discount!',
		cta: '👉 Get Discount',
		ticketLink:
			'https://ti.to/cityjs-conference/cityjs-athens-2025/discount/meetjs',
		eventLink: 'https://cityjsconf.org/athens',
		expiresAt: '2025-05-24T23:59:59+02:00',
		description:
			'CityJS Athens brings together JavaScript developers for two days of talks, workshops and networking in the heart of Greece. Join experts and enthusiasts to explore the latest in JS frameworks, tools, and best practices.',
		gradient: 'bg-gradient-to-r from-blue via-purple to-green',
		icon: '🚀',
		emojiRight: '🇬🇷',
		country: 'Greece',
		city: 'Athens',
		discountCode: 'meetjs',
	},
	{
		id: 'appjs-2025',
		message: 'App.js 2025: Exclusive 15% discount for meet.js community!',
		cta: '👉 Get 15% Off',
		ticketLink: 'https://ti.to/appjs/2025/discount/meetJS',
		eventLink: 'https://appjs.co',
		expiresAt: '2025-07-28T23:59:59+02:00',
		description:
			"App.js is Poland's premier conference focused on JavaScript for mobile and web applications. Join us in Kraków for hands-on workshops, in-depth technical talks, and networking with the top JS developers building modern applications.",
		gradient: 'bg-gradient-to-r from-indigo-500 via-blue-500 to-purple-500',
		icon: '📱',
		emojiRight: '🇵🇱',
		country: 'Poland',
		city: 'Kraków',
		discountCode: 'meetJS',
	},
	{
		id: 'react-universe-2025',
		message: 'React Universe Conf 2025: 10% off with code meet.js10!',
		cta: '👉 Get Discount',
		ticketLink: 'https://ti.to/RUC/react-universe-conf-2025/discount/meet.js10',
		eventLink: 'https://www.reactuniverseconf.com/',
		expiresAt: '2025-09-02T23:59:59+02:00',
		description:
			'React Universe is the largest React conference in Central Europe, bringing together the global React community in Wrocław, Poland. Featuring speakers from Meta and leading React teams, this event covers everything from React core concepts to advanced patterns and the React ecosystem.',
		gradient: 'bg-gradient-to-r from-yellow-400 via-orange-500 to-pink-500',
		icon: '🪐',
		emojiRight: '🇵🇱',
		country: 'Poland',
		city: 'Wrocław',
		discountCode: 'meet.js10',
	},
	{
		id: 'vueconfus-2025',
		message: 'VueConf US 2025: Use code VUE25MEETJS for a special discount!',
		cta: '👉 Redeem Voucher',
		ticketLink:
			'https://reg.connectevents.io/ConnectEvents/Vueconfus2025/redeem?voucher=VUE25MEETJS',
		eventLink: 'https://vueconf.us',
		expiresAt: '2025-05-21T23:59:59+02:00',
		description:
			'VueConf US is the premier Vue.js conference in North America, held in New Orleans on May 20-21, 2025. Join for two days of code playground, talks, and networking with the Vue community. Optional workshop day available on May 19. Save $199 with our exclusive discount!',
		gradient: 'bg-gradient-to-r from-green-400 via-blue-500 to-purple-500',
		icon: '🟩',
		emojiRight: '🇺🇸',
		country: 'USA',
		city: 'New Orleans',
		discountCode: 'VUE25MEETJS',
	},
	{
		id: 'summit-community-partner-2025',
		message: 'Women in Tech Summit: Use code SUMMIT_2025MEET.JS50 by May 17!',
		cta: '👉 Get tickets',
		ticketLink: 'https://go.womenintechsummit.pl/buy?inperson=1',
		eventLink: 'https://womenintechsummit.pl/join-the-event',
		expiresAt: '2025-05-17T23:59:59+02:00',
		description:
			'As a Community Partner for the Women in Tech Summit, meet.js members can use code SUMMIT_2025MEET.JS50 for 50% off tickets until May 17, 2025. Free tickets are also available - grab them as soon as possible for the best experience! The Summit offers networking with tech professionals, inspiring talks, and workshops. Join us and be part of this empowering event!',
		gradient: 'bg-gradient-to-r from-pink-500 via-yellow-400 to-purple-500',
		icon: '👧',
		emojiRight: '🇵🇱',
		country: 'Poland',
		city: 'Warsaw',
		discountCode: 'SUMMIT_2025MEET.JS50',
	},
	{
		id: 'react-summit-2025',
		message: 'React Summit 2025: 10% off with code REACT!',
		cta: '👉 Get 10% Off',
		ticketLink: 'https://ti.to/gitnation/react-summit-2025/discount/REACT',
		eventLink: 'https://gitnation.com/events/react-summit-2025',
		expiresAt: '2025-05-31T23:59:59+02:00',
		description:
			'React Summit 2025 brings together the global React community for an immersive experience with expert-led sessions and networking opportunities. Use code REACT for 10% off on tickets!',
		gradient: 'bg-gradient-to-r from-blue-600 via-indigo-500 to-purple-500',
		icon: '⚛️',
		emojiRight: '🇳🇱',
		country: 'Holland',
		city: 'Amsterdam',
		discountCode: 'REACT',
	},
	{
		id: 'react-summit-us-2025',
		message: 'React Summit US 2025: 10% off with code FRIENDS!',
		cta: '👉 Get 10% Off',
		ticketLink: 'https://ti.to/gitnation/react-summit-us-2025/discount/FRIENDS',
		eventLink: 'https://gitnation.com/events/react-summit-us-2025',
		expiresAt: '2025-09-30T23:59:59+02:00',
		description:
			'React Summit US 2025 is the premier React conference in North America. Join the global React community for expert-led sessions and networking. Use code FRIENDS for 10% off on tickets (available from July 1st)!',
		gradient: 'bg-gradient-to-r from-red-500 via-blue-500 to-indigo-600',
		icon: '⚛️',
		emojiRight: '🇺🇸',
		country: 'USA',
		city: 'New York',
		discountCode: 'FRIENDS',
	},
];
